skinparam shadowing false
skinparam backgroundColor white
skinparam ParticipantBackgroundColor #C0FFFF
skinparam ParticipantBorderColor #1E90FF
skinparam ActorBackgroundColor #C0FFFF
skinparam ActorBorderColor #1E90FF
skinparam SequenceLifeLineBorderColor #1E90FF
skinparam SequenceLifeLineBackgroundColor #C0FFFF
skinparam SequenceGroupBackgroundColor #C0FFFF
skinparam SequenceGroupBorderColor #1E90FF
skinparam SequenceGroupBorderThickness 2
skinparam ArrowColor black
skinparam ActivityBackgroundColor #C0FFFF
skinparam ActivityBorderColor #1E90FF
skinparam ActivityDiamondBackgroundColor #C0FFFF
skinparam ActivityDiamondBorderColor #1E90FF
skinparam TitleFontSize 12
skinparam TitleFontStyle bold
